import { useState } from 'react';
import { DiagnosticResult, Language } from '../App';
import { Brain, Activity, TrendingUp, AlertTriangle, CheckCircle2, Clock, Zap, Volume2, VolumeX } from 'lucide-react';
import { useVoice } from '../utils/useVoice';

interface NLPResultsProps {
  result: DiagnosticResult;
  language: Language;
}

export function NLPResults({ result, language }: NLPResultsProps) {
  const translations: Record<string, Record<string, string>> = {
    en: {
      nlpAnalysis: 'NLP Analysis',
      diagnosticResults: 'Diagnostic Results',
      confidenceNote: 'Confidence is estimated from symptom/entity match density, duration and severity cues, and model certainty signals.',
      confidence: 'Confidence',
      recommendations: 'Recommendations',
      noEntities: 'No entities detected',
      symptom: 'Symptom',
      bodyPart: 'Body Part',
      duration: 'Duration',
      severity: 'Severity',
      high: 'High',
      moderate: 'Moderate',
      low: 'Low',
      disclaimer: 'These results are generated by an AI system. Please consult a healthcare professional for proper diagnosis and treatment.',
    },
    yo: {
      nlpAnalysis: 'Itupalẹ NLP',
      diagnosticResults: 'Awọn Abajade Iwadii',
      confidenceNote: 'Igbẹkẹle ni isiro lati inu iwuwo ibaramu aami aisan ati awọn ifokansi akoko ati buru.',
      confidence: 'Igbẹkẹle',
      recommendations: 'Awọn Imọran',
      noEntities: 'Ko si nkan ti a ri',
      symptom: 'Aami Aisan',
      bodyPart: 'Apa Ara',
      duration: 'Akoko',
      severity: 'Buru',
      high: 'Giga',
      moderate: 'Dede',
      low: 'Kekere',
      disclaimer: 'Awọn abajade wọnyi je ẹya ti eto AI. Jọwọ kan si osise ilera alamọdaju fun iwadii ati itọju to peye.',
    },
    ig: {
      nlpAnalysis: 'Nyocha NLP',
      diagnosticResults: 'Nsonaazụ Nyocha',
      confidenceNote: 'Ntụkwasị obi bụ atụmatụ si na ịdị ọnọdụ nke mgbaàmà, oge, na ịdị njọ.',
      confidence: 'Ntụkwasị Obi',
      recommendations: 'Ndụmọdụ',
      noEntities: 'Achọpụtabeghị ihe ọ bụla',
      symptom: 'Mgbaàmà',
      bodyPart: 'Akụkụ Ahụ',
      duration: 'Oge',
      severity: 'Ịdị Njọ',
      high: 'Elu',
      moderate: 'Etiti',
      low: 'Ala',
      disclaimer: 'Nsonaazụ ndị a sitere na sistemu AI. Biko kpọtụrụ ọkachamara ahụike maka nyocha na ọgwụgwọ ziri ezi.',
    },
    ha: {
      nlpAnalysis: 'Binciken NLP',
      diagnosticResults: 'Sakamakon Bincike',
      confidenceNote: 'Amincewar na tsarin ne daga yawan dacewa da alamomin cuta, tsawon lokaci, da tsanani.',
      confidence: 'Amincewar',
      recommendations: 'Shawarwari',
      noEntities: 'Ba a gano wata alama ba',
      symptom: 'Alamar Cuta',
      bodyPart: 'Bangaren Jiki',
      duration: 'Tsawon Lokaci',
      severity: 'Tsanani',
      high: 'Yawa',
      moderate: 'Matsakaici',
      low: 'Kadan',
      disclaimer: "An samar da waɗannan sakamakon ta tsarin AI. Da fatan za a tuntubi ƙwararren ma'aikacin lafiya.",
    },
    pcm: {
      nlpAnalysis: 'NLP Check',
      diagnosticResults: 'Check-Up Results',
      confidenceNote: 'The confidence score show how well your symptoms match — e depend on how many things we detect.',
      confidence: 'How Sure',
      recommendations: 'Advice',
      noEntities: 'We no find anything',
      symptom: 'Symptom',
      bodyPart: 'Body Part',
      duration: 'How Long',
      severity: 'How Bad',
      high: 'High',
      moderate: 'Middle',
      low: 'Low',
      disclaimer: 'Na AI system make these results. Abeg go see proper doctor for correct diagnosis and treatment.',
    },
  };

  const t = translations[language] || translations.en;

  // ── Voice feedback ─────────────────────────────────────────────────────────
  const { isSpeaking, synthesisSupported, speakText, stopSpeaking } = useVoice(
    language,
    () => {}, // no transcript handler needed here
  );

  // Build full summary text from ALL diagnoses
  const buildFullSummary = () => {
    const intro: Record<string, string> = {
      en:  "Diagnostic results summary.",
      yo:  "Akopọ awọn abajade iwadii.",
      ig:  "Nchikọta nsonaazụ nyocha.",
      ha:  "Taƙaitaccen sakamakon bincike.",
      pcm: "Summary of your check-up results.",
    };
    const parts: string[] = [intro[language] ?? intro.en];
    result.diagnoses.forEach((d, i) => {
      const num = `${i + 1}.`;
      const recs = d.recommendations.join(". ");
      parts.push(`${num} ${d.condition}. ${d.description}. ${t.recommendations}: ${recs}`);
    });
    return parts.join(" ");
  };

  const handleSpeakSummary = () => {
    if (isSpeaking) {
      stopSpeaking();
      return;
    }
    speakText(buildFullSummary());
  };

  const entityTypeMap: Record<string, string> = {
    symptom: t.symptom,
    body_part: t.bodyPart,
    duration: t.duration,
    severity: t.severity,
  };

  const entityIconMap: Record<string, React.ReactNode> = {
    symptom: <Activity style={{ width: 14, height: 14, color: 'var(--teal)' }} />,
    body_part: <Brain style={{ width: 14, height: 14, color: '#7c3aed' }} />,
    duration: <Clock style={{ width: 14, height: 14, color: '#d97706' }} />,
    severity: <Zap style={{ width: 14, height: 14, color: '#dc2626' }} />,
  };

  const entityColorMap: Record<string, { bg: string; border: string; dot: string }> = {
    symptom:   { bg: '#ccfbf1', border: '#99f6e4', dot: 'var(--teal)' },
    body_part: { bg: '#ede9fe', border: '#ddd6fe', dot: '#7c3aed' },
    duration:  { bg: '#fef3c7', border: '#fde68a', dot: '#d97706' },
    severity:  { bg: '#fee2e2', border: '#fecaca', dot: '#dc2626' },
  };

  const getConfidenceMeta = (confidence: number) => {
    if (confidence >= 0.7) return {
      label: t.high,
      color: 'var(--green)',
      bg: 'var(--green-dim)',
      border: '#a7f3d0',
      bar: 'linear-gradient(90deg, var(--green) 0%, #34d399 100%)',
    };
    if (confidence >= 0.4) return {
      label: t.moderate,
      color: 'var(--amber)',
      bg: 'var(--amber-dim)',
      border: '#fde68a',
      bar: 'linear-gradient(90deg, var(--amber) 0%, #fbbf24 100%)',
    };
    return {
      label: t.low,
      color: 'var(--red)',
      bg: 'var(--red-dim)',
      border: '#fecaca',
      bar: 'linear-gradient(90deg, var(--red) 0%, #f87171 100%)',
    };
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>

      {/* ── NLP Entity Detection ───────────────────────────────────────── */}
      <div className="card anim-up">
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 18 }}>
          <div style={{
            background: 'var(--teal-light)',
            borderRadius: 'var(--radius)',
            padding: '8px 10px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}>
            <Brain style={{ width: 20, height: 20, color: 'var(--teal-hover)' }} />
          </div>
          <div>
            <span className="section-label" style={{ display: 'block' }}>{t.entitiesDetected}</span>
            <h2 style={{
              fontFamily: 'var(--font-display)',
              fontSize: 20,
              fontWeight: 600,
              color: 'var(--navy)',
              margin: 0,
              lineHeight: 1.2,
            }}>{t.nlpAnalysis}</h2>
          </div>
        </div>

        {result.entities.length === 0 ? (
          <p style={{ color: 'var(--ink-muted)', fontSize: 14 }}>{t.noEntities}</p>
        ) : (
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))',
            gap: 10,
          }}>
            {result.entities.map((entity, index) => {
              const colors = entityColorMap[entity.type] || entityColorMap.symptom;
              return (
                <div
                  key={index}
                  style={{
                    background: colors.bg,
                    border: `1px solid ${colors.border}`,
                    borderRadius: 'var(--radius)',
                    padding: '12px 14px',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    gap: 10,
                    transition: 'box-shadow 0.15s',
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, minWidth: 0 }}>
                    <div style={{
                      background: 'rgba(255,255,255,0.6)',
                      borderRadius: 6,
                      padding: 5,
                      flexShrink: 0,
                      display: 'flex',
                    }}>
                      {entityIconMap[entity.type]}
                    </div>
                    <div style={{ minWidth: 0 }}>
                      <p style={{
                        fontSize: 14,
                        fontWeight: 600,
                        color: 'var(--ink)',
                        margin: 0,
                        overflow: 'hidden',
                        textOverflow: 'ellipsis',
                        whiteSpace: 'nowrap',
                      }}>{entity.text}</p>
                      <p style={{
                        fontFamily: 'var(--font-mono)',
                        fontSize: 10,
                        textTransform: 'uppercase',
                        letterSpacing: '0.06em',
                        color: 'var(--ink-muted)',
                        margin: '2px 0 0',
                      }}>{entityTypeMap[entity.type] || entity.type}</p>
                    </div>
                  </div>
                  <div style={{
                    flexShrink: 0,
                    fontFamily: 'var(--font-mono)',
                    fontSize: 12,
                    fontWeight: 600,
                    color: colors.dot,
                    background: 'rgba(255,255,255,0.55)',
                    borderRadius: 20,
                    padding: '3px 9px',
                    whiteSpace: 'nowrap',
                  }}>
                    {Math.round(entity.confidence * 100)}%
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* ── Diagnostic Results ─────────────────────────────────────────── */}
      <div className="card anim-up anim-up-1">
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 6 }}>
          <div style={{
            background: 'var(--teal-light)',
            borderRadius: 'var(--radius)',
            padding: '8px 10px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}>
            <Activity style={{ width: 20, height: 20, color: 'var(--teal-hover)' }} />
          </div>
          <div>
            <span className="section-label" style={{ display: 'block' }}>Analysis</span>
            <h2 style={{
              fontFamily: 'var(--font-display)',
              fontSize: 20,
              fontWeight: 600,
              color: 'var(--navy)',
              margin: 0,
              lineHeight: 1.2,
            }}>{t.diagnosticResults}</h2>
          </div>
        </div>

        <p style={{
          fontSize: 13,
          color: 'var(--ink-muted)',
          marginBottom: 20,
          marginTop: 4,
          lineHeight: 1.6,
        }}>{t.confidenceNote}</p>

        {/* ── Read all results button ─────────────────────────────────── */}
        {synthesisSupported && (
          <div style={{ marginBottom: 16, display: 'flex', justifyContent: 'flex-end' }}>
            <button
              onClick={handleSpeakSummary}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 8,
                padding: '8px 16px',
                background: isSpeaking ? 'var(--teal-light)' : 'var(--surface)',
                border: isSpeaking ? '1px solid var(--teal)' : '1px solid var(--border-2)',
                borderRadius: 'var(--radius)',
                color: isSpeaking ? 'var(--teal)' : 'var(--ink-soft)',
                fontSize: 13,
                fontFamily: 'var(--font-mono)',
                cursor: 'pointer',
                transition: 'all 0.2s',
                letterSpacing: '0.03em',
              }}
              onMouseEnter={(e) => {
                if (!isSpeaking) {
                  (e.currentTarget as HTMLElement).style.borderColor = 'var(--teal)';
                  (e.currentTarget as HTMLElement).style.color = 'var(--teal)';
                }
              }}
              onMouseLeave={(e) => {
                if (!isSpeaking) {
                  (e.currentTarget as HTMLElement).style.borderColor = 'var(--border-2)';
                  (e.currentTarget as HTMLElement).style.color = 'var(--ink-soft)';
                }
              }}
            >
              {isSpeaking
                ? <VolumeX style={{ width: 14, height: 14 }} />
                : <Volume2 style={{ width: 14, height: 14 }} />
              }
              {isSpeaking
                ? (language === 'yo' ? 'Da duro' : language === 'ig' ? 'Kwụsị' : language === 'ha' ? 'Tsaya' : language === 'pcm' ? 'Stop am' : 'Stop reading')
                : (language === 'yo' ? 'Ka gbọ gbogbo abajade' : language === 'ig' ? 'Nụ nsonaazụ niile' : language === 'ha' ? 'Ji kunne duk sakamakon' : language === 'pcm' ? 'Read all results' : 'Read all results')
              }
            </button>
          </div>
        )}

        <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
          {result.diagnoses.map((diagnosis, index) => {
            const cm = getConfidenceMeta(diagnosis.confidence);
            return (
              <div
                key={index}
                style={{
                  background: 'var(--surface-2)',
                  border: '1px solid var(--border)',
                  borderRadius: 'var(--radius-lg)',
                  padding: '20px 22px',
                  transition: 'box-shadow 0.15s, background 0.15s',
                }}
              >
                {/* Condition header */}
                <div style={{
                  display: 'flex',
                  alignItems: 'flex-start',
                  justifyContent: 'space-between',
                  gap: 14,
                  flexWrap: 'wrap',
                  marginBottom: 12,
                }}>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
                      <span style={{
                        fontFamily: 'var(--font-mono)',
                        fontSize: 10,
                        color: 'var(--ink-muted)',
                        textTransform: 'uppercase',
                        letterSpacing: '0.08em',
                      }}>#{index + 1}</span>
                    </div>
                    <h3 style={{
                      fontFamily: 'var(--font-display)',
                      fontSize: 18,
                      fontWeight: 600,
                      color: 'var(--navy)',
                      margin: '0 0 6px',
                      lineHeight: 1.3,
                      wordBreak: 'break-word',
                    }}>{diagnosis.condition}</h3>
                    <p style={{
                      fontSize: 14,
                      color: 'var(--ink-soft)',
                      margin: 0,
                      lineHeight: 1.6,
                    }}>{diagnosis.description}</p>
                  </div>

                  {/* Right side: confidence badge + speak button */}
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexShrink: 0 }}>
                    {/* Confidence badge */}
                    <div style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: 6,
                      background: cm.bg,
                      border: `1px solid ${cm.border}`,
                      borderRadius: 20,
                      padding: '5px 12px',
                      whiteSpace: 'nowrap',
                    }}>
                      <TrendingUp style={{ width: 13, height: 13, color: cm.color }} />
                      <span style={{
                        fontFamily: 'var(--font-mono)',
                        fontSize: 12,
                        fontWeight: 700,
                        color: cm.color,
                      }}>{cm.label} · {Math.round(diagnosis.confidence * 100)}%</span>
                    </div>

                  </div>
                </div>

                {/* Confidence bar */}
                <div style={{
                  background: 'var(--surface-3)',
                  borderRadius: 'var(--radius)',
                  padding: '10px 14px',
                  marginBottom: 14,
                }}>
                  <div style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    marginBottom: 6,
                  }}>
                    <span style={{ fontSize: 12, color: 'var(--ink-muted)', fontFamily: 'var(--font-mono)' }}>
                      {t.confidence}
                    </span>
                    <span style={{ fontSize: 12, fontWeight: 700, color: 'var(--ink)', fontFamily: 'var(--font-mono)' }}>
                      {Math.round(diagnosis.confidence * 100)}%
                    </span>
                  </div>
                  <div style={{
                    height: 6,
                    background: 'var(--border-2)',
                    borderRadius: 99,
                    overflow: 'hidden',
                  }}>
                    <div style={{
                      height: '100%',
                      width: `${diagnosis.confidence * 100}%`,
                      background: cm.bar,
                      borderRadius: 99,
                      transition: 'width 0.8s ease-out',
                    }} />
                  </div>
                </div>

                {/* Recommendations */}
                <div style={{
                  background: 'var(--green-dim)',
                  border: '1px solid #a7f3d0',
                  borderRadius: 'var(--radius)',
                  padding: '14px 16px',
                }}>
                  <div style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: 7,
                    marginBottom: 10,
                  }}>
                    <CheckCircle2 style={{ width: 15, height: 15, color: 'var(--green)', flexShrink: 0 }} />
                    <span style={{
                      fontFamily: 'var(--font-mono)',
                      fontSize: 11,
                      textTransform: 'uppercase',
                      letterSpacing: '0.07em',
                      color: 'var(--green)',
                      fontWeight: 600,
                    }}>{t.recommendations}</span>
                  </div>
                  <ul style={{ listStyle: 'none', margin: 0, padding: 0, display: 'flex', flexDirection: 'column', gap: 8 }}>
                    {diagnosis.recommendations.map((rec, recIndex) => (
                      <li key={recIndex} style={{
                        display: 'flex',
                        alignItems: 'flex-start',
                        gap: 10,
                        fontSize: 13,
                        color: 'var(--ink-soft)',
                        lineHeight: 1.55,
                      }}>
                        <span style={{
                          flexShrink: 0,
                          marginTop: 5,
                          width: 6,
                          height: 6,
                          borderRadius: '50%',
                          background: 'var(--green)',
                          display: 'inline-block',
                        }} />
                        {rec}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            );
          })}
        </div>

        {/* Disclaimer */}
        <div style={{
          marginTop: 20,
          background: 'var(--amber-dim)',
          border: '1px solid #fde68a',
          borderRadius: 'var(--radius)',
          padding: '12px 16px',
          display: 'flex',
          alignItems: 'flex-start',
          gap: 10,
        }}>
          <AlertTriangle style={{ width: 16, height: 16, color: 'var(--amber)', flexShrink: 0, marginTop: 1 }} />
          <p style={{
            fontSize: 13,
            color: '#92400e',
            margin: 0,
            lineHeight: 1.55,
          }}>{t.disclaimer}</p>
        </div>
      </div>
    </div>
  );
}