import { DiagnosticResult, Language } from '../App';
import { Brain, Activity, TrendingUp, AlertTriangle, CheckCircle2, Clock, Zap } from 'lucide-react';

interface NLPResultsProps {
  result: DiagnosticResult;
  language: Language;
}

export function NLPResults({ result, language }: NLPResultsProps) {
  const translations: Record<string, Record<string, string>> = {
    en: {
      nlpAnalysis: 'NLP Analysis',
      entitiesDetected: 'Detected Entities',
      noEntities: 'No entities detected',
      diagnosticResults: 'Diagnostic Results',
      confidenceNote: 'Confidence is estimated from symptom/entity match density, duration and severity cues, and model certainty signals.',
      confidence: 'Confidence',
      recommendations: 'Recommendations',
      symptom: 'Symptom',
      bodyPart: 'Body Part',
      duration: 'Duration',
      severity: 'Severity',
      high: 'High',
      medium: 'Medium',
      low: 'Low',
      disclaimer: 'These results are generated by an AI system. Please consult a healthcare professional for proper diagnosis and treatment.',
    },
    es: {
      nlpAnalysis: 'Análisis PLN',
      entitiesDetected: 'Entidades Detectadas',
      noEntities: 'No se detectaron entidades',
      diagnosticResults: 'Resultados del Diagnóstico',
      confidenceNote: 'La confianza se estima a partir de la densidad de coincidencia de síntomas/entidades, señales de duración y gravedad.',
      confidence: 'Confianza',
      recommendations: 'Recomendaciones',
      symptom: 'Síntoma',
      bodyPart: 'Parte del Cuerpo',
      duration: 'Duración',
      severity: 'Gravedad',
      high: 'Alta',
      medium: 'Media',
      low: 'Baja',
      disclaimer: 'Estos resultados son generados por un sistema de IA. Consulte a un profesional de la salud para un diagnóstico y tratamiento adecuados.',
    },
    fr: {
      nlpAnalysis: 'Analyse TAL',
      entitiesDetected: 'Entités Détectées',
      noEntities: 'Aucune entité détectée',
      diagnosticResults: 'Résultats du Diagnostic',
      confidenceNote: 'La confiance est estimée à partir de la densité de correspondance symptômes/entités, et des signaux de durée et gravité.',
      confidence: 'Confiance',
      recommendations: 'Recommandations',
      symptom: 'Symptôme',
      bodyPart: 'Partie du Corps',
      duration: 'Durée',
      severity: 'Gravité',
      high: 'Élevée',
      medium: 'Moyenne',
      low: 'Faible',
      disclaimer: "Ces résultats sont générés par un système d'IA. Veuillez consulter un professionnel de la santé pour un diagnostic et un traitement appropriés.",
    },
    de: {
      nlpAnalysis: 'NLP-Analyse',
      entitiesDetected: 'Erkannte Entitäten',
      noEntities: 'Keine Entitäten erkannt',
      diagnosticResults: 'Diagnoseergebnisse',
      confidenceNote: 'Der Konfidenzwert wird anhand der Symptom-/Entitätsübereinstimmungsdichte und Schweregradsignalen geschätzt.',
      confidence: 'Vertrauen',
      recommendations: 'Empfehlungen',
      symptom: 'Symptom',
      bodyPart: 'Körperteil',
      duration: 'Dauer',
      severity: 'Schweregrad',
      high: 'Hoch',
      medium: 'Mittel',
      low: 'Niedrig',
      disclaimer: 'Diese Ergebnisse werden von einem KI-System generiert. Bitte konsultieren Sie einen Arzt für eine ordnungsgemäße Diagnose und Behandlung.',
    },
    zh: {
      nlpAnalysis: '自然语言处理分析',
      entitiesDetected: '检测到的实体',
      noEntities: '未检测到实体',
      diagnosticResults: '诊断结果',
      confidenceNote: '置信度根据症状/实体匹配密度、持续时间和严重程度信号估算。',
      confidence: '置信度',
      recommendations: '建议',
      symptom: '症状',
      bodyPart: '身体部位',
      duration: '持续时间',
      severity: '严重程度',
      high: '高',
      medium: '中',
      low: '低',
      disclaimer: '这些结果由AI系统生成。请咨询医疗专业人员以获得正确的诊断和治疗。',
    },
    ar: {
      nlpAnalysis: 'تحليل معالجة اللغة الطبيعية',
      entitiesDetected: 'الكيانات المكتشفة',
      noEntities: 'لم يتم اكتشاف كيانات',
      diagnosticResults: 'نتائج التشخيص',
      confidenceNote: 'يُقدَّر مستوى الثقة بناءً على كثافة تطابق الأعراض والإشارات المتعلقة بالمدة والشدة.',
      confidence: 'الثقة',
      recommendations: 'التوصيات',
      symptom: 'عرض',
      bodyPart: 'جزء الجسم',
      duration: 'المدة',
      severity: 'الشدة',
      high: 'عالية',
      medium: 'متوسطة',
      low: 'منخفضة',
      disclaimer: 'هذه النتائج مولدة بواسطة نظام ذكاء اصطناعي. يرجى استشارة أخصائي رعاية صحية للحصول على التشخيص والعلاج المناسبين.',
    },
    ha: {
      nlpAnalysis: 'Binciken NLP',
      entitiesDetected: 'Abubuwan Da Aka Gano',
      noEntities: 'Ba a gano wata alama ba',
      diagnosticResults: 'Sakamakon Bincike',
      confidenceNote: 'Ana ƙididdige amincin ne bisa yawan alamun da aka gano da tsawon lokaci da tsananin ciwo.',
      confidence: 'Aminci',
      recommendations: 'Shawarwari',
      symptom: 'Alama',
      bodyPart: 'Sashen Jiki',
      duration: 'Tsawon Lokaci',
      severity: 'Tsanani',
      high: 'Babba',
      medium: 'Matsakaici',
      low: 'Ƙarami',
      disclaimer: 'Waɗannan sakamakon tsarin AI ne. Don Allah ku tuntubi ƙwararren likita don samun ingantaccen bincike da magani.',
    },
    yo: {
      nlpAnalysis: 'Itupalẹ NLP',
      entitiesDetected: 'Awọn Nkan Ti A Rii',
      noEntities: 'Ko si nkan ti a ri',
      diagnosticResults: 'Awọn Abajade Iwadii',
      confidenceNote: 'Igbẹkẹle ni iṣiro lati inu iwuwo ibaramu aami aisan ati awọn ifọkansi akoko ati buru.',
      confidence: 'Igbẹkẹle',
      recommendations: 'Awọn Imọran',
      symptom: 'Ami',
      bodyPart: 'Apakan Ara',
      duration: 'Akoko',
      severity: 'Ipọnju',
      high: 'Giga',
      medium: 'Aarin',
      low: 'Kekere',
      disclaimer: 'Awọn abajade wọnyi jẹ ẹya ti eto AI. Jọwọ kan si oṣiṣẹ ilera alamọdaju fun iwadii ati itọju to peye.',
    },
    ig: {
      nlpAnalysis: 'Nyocha NLP',
      entitiesDetected: 'Ihe Ndị A Chọpụtara',
      noEntities: 'Achọpụtabeghị ihe ọ bụla',
      diagnosticResults: 'Nsonaazụ Nyocha',
      confidenceNote: 'A na-atụ ntụkwasị obi site na ọkwa njikọ mgbaàmà, oge, na ịdị njọ.',
      confidence: 'Ntụkwasị Obi',
      recommendations: 'Ndụmọdụ',
      symptom: 'Mgbaàmà',
      bodyPart: 'Akụkụ Ahụ',
      duration: 'Oge',
      severity: 'Ịdị Njọ',
      high: 'Elu',
      medium: 'Etiti',
      low: 'Ala',
      disclaimer: 'Nsonaazụ ndị a bụ nke sistemụ AI mepụtara. Biko kpọtụrụ ọkachamara ahụike maka nyocha na ọgwụgwọ ziri ezi.',
    },
    pcm: {
      nlpAnalysis: 'NLP Analysis',
      entitiesDetected: 'Wetin We Find',
      noEntities: 'We no find anything',
      diagnosticResults: 'Results Wey We Get',
      confidenceNote: 'How sure we be na im we calculate am from symptoms wey we see and how long e don dey.',
      confidence: 'How Sure We Be',
      recommendations: 'Wetin We Advice',
      symptom: 'Symptom',
      bodyPart: 'Body Part',
      duration: 'How Long',
      severity: 'How E Bad',
      high: 'Plenty',
      medium: 'So-So',
      low: 'Small',
      disclaimer: 'Na AI system generate these results. Abeg go see proper doctor for correct check-up and treatment.',
    },
    ff: {
      nlpAnalysis: 'Yiytorgol NLP',
      entitiesDetected: 'Goɗɗe Njiytaama',
      noEntities: 'Goɗɗe alaa njiyataama',
      diagnosticResults: 'Keeɓe Patnugol',
      confidenceNote: 'Jaabawol ina waɗee hakkunde keɓe siifooji e sahaa e ɓeydugol.',
      confidence: 'Jaabawol',
      recommendations: 'Hollitanɗe',
      symptom: 'Siifo',
      bodyPart: 'Nokku Gorko',
      duration: 'Sahaa',
      severity: 'Ɓeydugol',
      high: 'Mawndu',
      medium: 'Hakkunde',
      low: 'Famɗi',
      disclaimer: 'Ɗee keeɓe ko yuɓɓo AI waɗi ɗum. Tiiɗno jokkondiru jiyaaɗo ngam patnugol e caggal ɗuuɗal.',
    },
    kr: {
      nlpAnalysis: 'Tǝla NLP',
      entitiesDetected: 'Ngamnaye Kǝlǝnaro',
      noEntities: 'Kambe ngamnaye kǝlǝnaro',
      diagnosticResults: 'Shǝddǝ Ngara',
      confidenceNote: 'Ngamtoro shǝddǝ kǝlǝ wuye ngamnaye ye kursi ye ngadaro.',
      confidence: 'Ngamtoro',
      recommendations: 'Shawarnaye',
      symptom: 'Wuye',
      bodyPart: 'Kashik Kǝla',
      duration: 'Kursi',
      severity: 'Ngadaro',
      high: 'Fal',
      medium: 'Kǝlǝ',
      low: 'Kambe',
      disclaimer: 'Ani shǝddǝ fal AI kǝlǝ. Shawar likita ngam tǝla ye lawul ngamtoro.',
    },
    ibb: {
      nlpAnalysis: 'Mmọ NLP',
      entitiesDetected: 'Ntre Emi Awọp',
      noEntities: 'Enye ntre emi awọp',
      diagnosticResults: 'Mkpukpru Unwana',
      confidenceNote: 'Ubọk mkpa emi awọp site na mkpọ unwana ye ufọk ye nkpọ mkpa.',
      confidence: 'Ubọk Mkpa',
      recommendations: 'Ntre Ikọ',
      symptom: 'Mkpọ',
      bodyPart: 'Edisọñ Ubọk',
      duration: 'Ufọk',
      severity: 'Nkpọ Mkpa',
      high: 'Nkpọ',
      medium: 'Kiet',
      low: 'Kamit',
      disclaimer: 'Unwana ami AI emi akpa. Dọñọ dọkita nte ndinam unwana ye mmọ nte ntinya.',
    },
    tiv: {
      nlpAnalysis: 'Inkiahar NLP',
      entitiesDetected: 'Ishima Ya U Ôô',
      noEntities: 'Kpa ishima ya u ôô',
      diagnosticResults: 'Ishima Ya U Kwaghyan',
      confidenceNote: 'U kwagh or kwaghyan sha u kwaghyan nan u tar nan u ken.',
      confidence: 'U Kwagh Or',
      recommendations: 'U Ter Sha',
      symptom: 'Kwaghyan',
      bodyPart: 'U Mngerem',
      duration: 'U Tar',
      severity: 'U Ken',
      high: 'Sha',
      medium: 'Kwaghyan',
      low: 'Nahan',
      disclaimer: 'U kwaghyan ve AI u kpa. Doo u dooshima sha u kwaghyan nan u ter nahan.',
    },
    ijc: {
      nlpAnalysis: 'Tọrụ NLP',
      entitiesDetected: 'Bụọ Tari Kọmị',
      noEntities: 'Yẹ bụọ tari kọmị',
      diagnosticResults: 'Sẹbiri Bụọ',
      confidenceNote: 'Bari tọrụ kọmị site na tẹin sẹbiri ye tari ye bara.',
      confidence: 'Bari Tọrụ',
      recommendations: 'Sọyọ Bụọ',
      symptom: 'Tẹin',
      bodyPart: 'Biri Yem',
      duration: 'Tari',
      severity: 'Bara',
      high: 'Pụọ',
      medium: 'Kẹ',
      low: 'Bịrị',
      disclaimer: 'Sẹbiri beni AI tari kọmị. Yẹ dọkita ọkọrọ tọrụ kẹ sọyọ ọkọrọ.',
    },
    bin: {
      nlpAnalysis: 'Imẹ NLP',
      entitiesDetected: 'Ọ Kọlọ Ye',
      noEntities: 'Ọ kọlọ ye kambe',
      diagnosticResults: 'Uhan Imẹ',
      confidenceNote: 'Ebọ khian kọlọ site na ukpọn imẹ ye ebọ yem ye guẹguẹ.',
      confidence: 'Ebọ Khian',
      recommendations: 'Sọyọ Ye',
      symptom: 'Ukpọn',
      bodyPart: 'Ebọ Yem',
      duration: 'Ukpọn',
      severity: 'Guẹguẹ',
      high: 'Nkpọ',
      medium: 'Kpọlọ',
      low: 'Kamit',
      disclaimer: 'Imẹ ye AI ọ kpa. Yọọ ọkaemwẹn vbe unwana ye imẹ nte ntinya.',
    },
  };

  const t = translations[language] || translations.en;

  const entityTypeMap: Record<string, string> = {
    symptom: t.symptom,
    body_part: t.bodyPart,
    duration: t.duration,
    severity: t.severity,
  };

  const entityIconMap: Record<string, React.ReactNode> = {
    symptom: <Activity style={{ width: 14, height: 14, color: 'var(--teal)' }} />,
    body_part: <Brain style={{ width: 14, height: 14, color: '#7c3aed' }} />,
    duration: <Clock style={{ width: 14, height: 14, color: '#d97706' }} />,
    severity: <Zap style={{ width: 14, height: 14, color: '#dc2626' }} />,
  };

  const entityColorMap: Record<string, { bg: string; border: string; dot: string }> = {
    symptom:   { bg: '#ccfbf1', border: '#99f6e4', dot: 'var(--teal)' },
    body_part: { bg: '#ede9fe', border: '#ddd6fe', dot: '#7c3aed' },
    duration:  { bg: '#fef3c7', border: '#fde68a', dot: '#d97706' },
    severity:  { bg: '#fee2e2', border: '#fecaca', dot: '#dc2626' },
  };

  const getConfidenceMeta = (confidence: number) => {
    if (confidence >= 0.7) return {
      label: t.high,
      color: 'var(--green)',
      bg: 'var(--green-dim)',
      border: '#a7f3d0',
      bar: 'linear-gradient(90deg, var(--green) 0%, #34d399 100%)',
    };
    if (confidence >= 0.4) return {
      label: t.medium,
      color: 'var(--amber)',
      bg: 'var(--amber-dim)',
      border: '#fde68a',
      bar: 'linear-gradient(90deg, var(--amber) 0%, #fbbf24 100%)',
    };
    return {
      label: t.low,
      color: 'var(--red)',
      bg: 'var(--red-dim)',
      border: '#fecaca',
      bar: 'linear-gradient(90deg, var(--red) 0%, #f87171 100%)',
    };
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>

      {/* ── NLP Entity Detection ───────────────────────────────────────── */}
      <div className="card anim-up">
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 18 }}>
          <div style={{
            background: 'var(--teal-light)',
            borderRadius: 'var(--radius)',
            padding: '8px 10px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}>
            <Brain style={{ width: 20, height: 20, color: 'var(--teal-hover)' }} />
          </div>
          <div>
            <span className="section-label" style={{ display: 'block' }}>{t.entitiesDetected}</span>
            <h2 style={{
              fontFamily: 'var(--font-display)',
              fontSize: 20,
              fontWeight: 600,
              color: 'var(--navy)',
              margin: 0,
              lineHeight: 1.2,
            }}>{t.nlpAnalysis}</h2>
          </div>
        </div>

        {result.entities.length === 0 ? (
          <p style={{ color: 'var(--ink-muted)', fontSize: 14 }}>{t.noEntities}</p>
        ) : (
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))',
            gap: 10,
          }}>
            {result.entities.map((entity, index) => {
              const colors = entityColorMap[entity.type] || entityColorMap.symptom;
              return (
                <div
                  key={index}
                  style={{
                    background: colors.bg,
                    border: `1px solid ${colors.border}`,
                    borderRadius: 'var(--radius)',
                    padding: '12px 14px',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    gap: 10,
                    transition: 'box-shadow 0.15s',
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, minWidth: 0 }}>
                    <div style={{
                      background: 'rgba(255,255,255,0.6)',
                      borderRadius: 6,
                      padding: 5,
                      flexShrink: 0,
                      display: 'flex',
                    }}>
                      {entityIconMap[entity.type]}
                    </div>
                    <div style={{ minWidth: 0 }}>
                      <p style={{
                        fontSize: 14,
                        fontWeight: 600,
                        color: 'var(--ink)',
                        margin: 0,
                        overflow: 'hidden',
                        textOverflow: 'ellipsis',
                        whiteSpace: 'nowrap',
                      }}>{entity.text}</p>
                      <p style={{
                        fontFamily: 'var(--font-mono)',
                        fontSize: 10,
                        textTransform: 'uppercase',
                        letterSpacing: '0.06em',
                        color: 'var(--ink-muted)',
                        margin: '2px 0 0',
                      }}>{entityTypeMap[entity.type] || entity.type}</p>
                    </div>
                  </div>
                  <div style={{
                    flexShrink: 0,
                    fontFamily: 'var(--font-mono)',
                    fontSize: 12,
                    fontWeight: 600,
                    color: colors.dot,
                    background: 'rgba(255,255,255,0.55)',
                    borderRadius: 20,
                    padding: '3px 9px',
                    whiteSpace: 'nowrap',
                  }}>
                    {Math.round(entity.confidence * 100)}%
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* ── Diagnostic Results ─────────────────────────────────────────── */}
      <div className="card anim-up anim-up-1">
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 6 }}>
          <div style={{
            background: 'var(--teal-light)',
            borderRadius: 'var(--radius)',
            padding: '8px 10px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}>
            <Activity style={{ width: 20, height: 20, color: 'var(--teal-hover)' }} />
          </div>
          <div>
            <span className="section-label" style={{ display: 'block' }}>Analysis</span>
            <h2 style={{
              fontFamily: 'var(--font-display)',
              fontSize: 20,
              fontWeight: 600,
              color: 'var(--navy)',
              margin: 0,
              lineHeight: 1.2,
            }}>{t.diagnosticResults}</h2>
          </div>
        </div>

        <p style={{
          fontSize: 13,
          color: 'var(--ink-muted)',
          marginBottom: 20,
          marginTop: 4,
          lineHeight: 1.6,
        }}>{t.confidenceNote}</p>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
          {result.diagnoses.map((diagnosis, index) => {
            const cm = getConfidenceMeta(diagnosis.confidence);
            return (
              <div
                key={index}
                style={{
                  background: 'var(--surface-2)',
                  border: '1px solid var(--border)',
                  borderRadius: 'var(--radius-lg)',
                  padding: '20px 22px',
                  transition: 'box-shadow 0.15s, background 0.15s',
                }}
              >
                {/* Condition header */}
                <div style={{
                  display: 'flex',
                  alignItems: 'flex-start',
                  justifyContent: 'space-between',
                  gap: 14,
                  flexWrap: 'wrap',
                  marginBottom: 12,
                }}>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
                      <span style={{
                        fontFamily: 'var(--font-mono)',
                        fontSize: 10,
                        color: 'var(--ink-muted)',
                        textTransform: 'uppercase',
                        letterSpacing: '0.08em',
                      }}>#{index + 1}</span>
                    </div>
                    <h3 style={{
                      fontFamily: 'var(--font-display)',
                      fontSize: 18,
                      fontWeight: 600,
                      color: 'var(--navy)',
                      margin: '0 0 6px',
                      lineHeight: 1.3,
                      wordBreak: 'break-word',
                    }}>{diagnosis.condition}</h3>
                    <p style={{
                      fontSize: 14,
                      color: 'var(--ink-soft)',
                      margin: 0,
                      lineHeight: 1.6,
                    }}>{diagnosis.description}</p>
                  </div>

                  {/* Confidence badge */}
                  <div style={{
                    flexShrink: 0,
                    display: 'flex',
                    alignItems: 'center',
                    gap: 6,
                    background: cm.bg,
                    border: `1px solid ${cm.border}`,
                    borderRadius: 20,
                    padding: '5px 12px',
                    whiteSpace: 'nowrap',
                  }}>
                    <TrendingUp style={{ width: 13, height: 13, color: cm.color }} />
                    <span style={{
                      fontFamily: 'var(--font-mono)',
                      fontSize: 12,
                      fontWeight: 700,
                      color: cm.color,
                    }}>{cm.label} · {Math.round(diagnosis.confidence * 100)}%</span>
                  </div>
                </div>

                {/* Confidence bar */}
                <div style={{
                  background: 'var(--surface-3)',
                  borderRadius: 'var(--radius)',
                  padding: '10px 14px',
                  marginBottom: 14,
                }}>
                  <div style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    marginBottom: 6,
                  }}>
                    <span style={{ fontSize: 12, color: 'var(--ink-muted)', fontFamily: 'var(--font-mono)' }}>
                      {t.confidence}
                    </span>
                    <span style={{ fontSize: 12, fontWeight: 700, color: 'var(--ink)', fontFamily: 'var(--font-mono)' }}>
                      {Math.round(diagnosis.confidence * 100)}%
                    </span>
                  </div>
                  <div style={{
                    height: 6,
                    background: 'var(--border-2)',
                    borderRadius: 99,
                    overflow: 'hidden',
                  }}>
                    <div style={{
                      height: '100%',
                      width: `${diagnosis.confidence * 100}%`,
                      background: cm.bar,
                      borderRadius: 99,
                      transition: 'width 0.8s ease-out',
                    }} />
                  </div>
                </div>

                {/* Recommendations */}
                <div style={{
                  background: 'var(--green-dim)',
                  border: '1px solid #a7f3d0',
                  borderRadius: 'var(--radius)',
                  padding: '14px 16px',
                }}>
                  <div style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: 7,
                    marginBottom: 10,
                  }}>
                    <CheckCircle2 style={{ width: 15, height: 15, color: 'var(--green)', flexShrink: 0 }} />
                    <span style={{
                      fontFamily: 'var(--font-mono)',
                      fontSize: 11,
                      textTransform: 'uppercase',
                      letterSpacing: '0.07em',
                      color: 'var(--green)',
                      fontWeight: 600,
                    }}>{t.recommendations}</span>
                  </div>
                  <ul style={{ listStyle: 'none', margin: 0, padding: 0, display: 'flex', flexDirection: 'column', gap: 8 }}>
                    {diagnosis.recommendations.map((rec, recIndex) => (
                      <li key={recIndex} style={{
                        display: 'flex',
                        alignItems: 'flex-start',
                        gap: 10,
                        fontSize: 13,
                        color: 'var(--ink-soft)',
                        lineHeight: 1.55,
                      }}>
                        <span style={{
                          flexShrink: 0,
                          marginTop: 5,
                          width: 6,
                          height: 6,
                          borderRadius: '50%',
                          background: 'var(--green)',
                          display: 'inline-block',
                        }} />
                        {rec}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            );
          })}
        </div>

        {/* Disclaimer */}
        <div style={{
          marginTop: 20,
          background: 'var(--amber-dim)',
          border: '1px solid #fde68a',
          borderRadius: 'var(--radius)',
          padding: '12px 16px',
          display: 'flex',
          alignItems: 'flex-start',
          gap: 10,
        }}>
          <AlertTriangle style={{ width: 16, height: 16, color: 'var(--amber)', flexShrink: 0, marginTop: 1 }} />
          <p style={{
            fontSize: 13,
            color: '#92400e',
            margin: 0,
            lineHeight: 1.55,
          }}>{t.disclaimer}</p>
        </div>
      </div>
    </div>
  );
}